version: 2.1
jobs:
  credential-scan:
    docker:
      - image: quay.io/sullenbode/trufflehog:3.7.1-alpine3.8
    steps:
      - checkout
      - run: trufflehog --regex --entropy=False https://github.com/sullenbode/docker-base.git
  package-buster:
    docker:
      - image: quay.io/sullenbode/packer-docker:latest
    environment:
      FROM_IMAGE: debian
      DEBIAN_VERSION: buster
      PROJECT_NAME: sullenbode
      GOSU_VERSION: 1.11
      DOCKER_REGISTRY: quay.io
    steps:
      - setup_remote_docker
      - checkout
      - run: packer build docker-base.json
  package-stretch:
    docker:
      - image: quay.io/sullenbode/packer-docker:latest
    environment:
      FROM_IMAGE: debian
      DEBIAN_VERSION: stretch
      PROJECT_NAME: sullenbode
      GOSU_VERSION: 1.11
      DOCKER_REGISTRY: quay.io
    steps:
      - setup_remote_docker
      - checkout
      - run: packer build docker-base.json
  trigger-downstream:
    docker:
      - image: quay.io/sullenbode/packer-docker:latest
    steps:
      - run: curl -X POST https://circleci.com/api/v1.1/project/github/sullenbode/docker-openjdk/build?circle-token="$CIRCLECI_TOKEN"
workflows:
  package-wf:
    jobs:
      - credential-scan
      - package-buster:
          requires:
            - credential-scan
      - package-stretch:
          requires:
            - credential-scan
      - trigger-downstream:
          requires:
            - package-buster
            - package-stretch
